<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260421174000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create products, product attributes, and product images tables.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE products (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, external_code VARCHAR(255) NOT NULL, name VARCHAR(500) NOT NULL, description TEXT DEFAULT NULL, price NUMERIC(12, 2) NOT NULL, purchase_price NUMERIC(12, 2) DEFAULT NULL, discount_percent NUMERIC(8, 2) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_products_external_code ON products (external_code)');
        $this->addSql('CREATE TABLE product_attributes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_id INT NOT NULL, attribute_key VARCHAR(255) NOT NULL, attribute_value TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_48543B274584665A ON product_attributes (product_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_product_attribute_key ON product_attributes (product_id, attribute_key)');
        $this->addSql('CREATE TABLE product_images (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, product_id INT NOT NULL, source_url VARCHAR(2048) NOT NULL, local_path VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_64617F074584665A ON product_images (product_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_product_image_source_url ON product_images (product_id, source_url)');
        $this->addSql('ALTER TABLE product_attributes ADD CONSTRAINT FK_48543B274584665A FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_images ADD CONSTRAINT FK_64617F074584665A FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE product_attributes DROP CONSTRAINT FK_48543B274584665A');
        $this->addSql('ALTER TABLE product_images DROP CONSTRAINT FK_64617F074584665A');
        $this->addSql('DROP TABLE product_attributes');
        $this->addSql('DROP TABLE product_images');
        $this->addSql('DROP TABLE products');
    }
}
